HW1
Skiftare/Java2023 pull request #1
Opened 2023-10-07 06:08 UTC by Skiftare

2023-10-09 15:52 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +        int ans = -1;
обращай внимание на подсказки ide, стараемся держать в коде как можно меньше ворнингов, тк это плохой тон

2023-10-09 15:54 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +
между аннотациями и объектами над которыми она ставиться не нужно ставить отступы, давай уберем во всех классах)

2023-10-09 15:55 UTC, Skiftare commented on src/main/java/edu/hw1/Task1.java
> +
Сейчас будет

2023-10-09 15:58 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +        int tenMulti = 10;
можно кстати очень просто избегать случаев когда необходимо вешать supress для меджик намберов, например
```
    private static final Integer TEN_MULTI = 10;
```
и потом использовать это в коде, тогда и ворнингов не будет и код будет красивый)

2023-10-09 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +        for (int i = 0; i < s.length(); i++) {
кажется тут немного переусложнил, а что если попробовать: 
- функцией split от строки
- Integer.parseInt
- выполнять дальнейшую обработку чисел

2023-10-09 16:13 UTC, Skiftare commented on src/main/java/edu/hw1/Task1.java
> +        for (int i = 0; i < s.length(); i++) {
Окей. Решил просто, что строки в числа, долго, неэффективно... Сейчас сделаю так. Наследие спортпрога)

2023-10-09 16:13 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +        private static final Integer tenMulti = 10;
давай это вынесем прям в константы класса, и важно сохранять upper case snake case для констант, то есть так 
```
class Task1 {

    private static final Integer TEN_MULTI = 10;

    static int minutesToSeconds(@NotNull String s) {
        int secs = 0;
        boolean flag = false;
        int mins = 0;
```

2023-10-09 16:15 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task2Test.java
> +    void zero() {
а почему на этот метод не навесил аннотацию Test?

2023-10-09 16:16 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task2.java
> +    public static int countDigits(int n) {
тут тоже подумай какие константы можно вынести

2023-10-09 16:17 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task3.java
> +    public static boolean isNestable(int @NotNull [] fstMas, int[] secMas) {
обрати внимание на ворнинг, давай тоже избавимся от него

2023-10-09 16:21 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task3.java
> +                minFst = fstMas[i];
эту инициализацию можно вынести за пределы массива, только добавить проверку на длину массива перед этим

2023-10-09 16:23 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task1Test.java
> +    void zero_zero() {
все тесты необходимо именовать в camelCase, так же как и методы и пременные

2023-10-09 16:25 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task5Test.java
> +        assertEquals(true, Task5.isPalindromeDescendant(11211230));
можно воспользоваться `assertTrue`

2023-10-09 16:27 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task7.java
> +        buf = 0;
можно убрать

2023-10-09 16:31 UTC, kkkoltunov commented
в целом неплохо, молодец! поправь пожалуйста комменты и я вернусь еще раз с проверкой, из общего:
- старайся пользоваться возможностями ide, она подсвечивает много нюансов которые желательно исправлять (рекомендую Intelij Idea)
- в каждом классе делай автоформатирование кода, вот полезные хоткеи https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf
- старайся давать более осмысленное название переменным, не жалей символы, они бесплатные))

2023-10-09 17:31 UTC, Skiftare commented on src/main/java/edu/hw1/Task7.java
> +        buf = 0;
> можно убрать

Убрал, assertTrue/False переписал, camelCase сделал в тестах

2023-10-09 17:47 UTC, Skiftare commented on src/test/java/edu/hw1/Task5Test.java
> +        assertEquals(true, Task5.isPalindromeDescendant(11211230));
> можно воспользоваться `assertTrue`

Да, поправил. При этом это даже IDE предлагала, но я что-то проглядел этот момент

2023-10-09 17:47 UTC, Skiftare commented on src/main/java/edu/hw1/Task3.java
> +    public static boolean isNestable(int @NotNull [] fstMas, int[] secMas) {
> обрати внимание на ворнинг, давай тоже избавимся от него

Убрал бесполезный int ans;

2023-10-09 18:33 UTC, Skiftare commented
- [ ] Лучше после ревью править файлы, и потом выкатывать один большой коммит, либо по файлам идти и сразу отправлять (файл-коммит, файл-коммит...)? 
- [ ] И насколько гитхаб нормально делает code coverage? Idea показывает 100%, например, Task1. И вот где эти 5% искать? Писать тесты для чего, для импорта библиотек, инициализаций?

2023-10-10 16:34 UTC, kkkoltunov commented on src/main/java/edu/hw1/EvenArrayUtils.java
> +public final class EvenArrayUtils {
test

2023-10-10 16:46 UTC, kkkoltunov requested changes

2023-10-10 16:46 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +        int secs;
давай избегать именования переменных сокращенными словами, пиши плиз полностью `seconds`

2023-10-10 16:46 UTC, kkkoltunov commented on src/main/java/edu/hw1/Task1.java
> +    private static final Integer SIXTY_NUM = 60;
тут аналогично `SIXTY_NUMBER`, сейчас это не так важно, но учитывай что в будущем ты будешь работать в команде, твои сокомандники должны по названию переменной четко понимать что они делают 

поправь подобные нюансы пожалуйста в остальных частях кода

2023-10-10 16:46 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task1Test.java
> +
лишний пробел, такие есть еще, пробегись пожалуйста по своему коду

2023-10-10 16:46 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task1Test.java
> +    @Test
давай ко всем тест классам методов напишем `@DisplayName` и описание, чтобы мне было проще проверять

2023-10-10 16:46 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task1Test.java
> +    void a_lot_secs() {
тут тоже должен быть camelCase, проверь это пожалуйста **везде** в коде

2023-10-10 16:46 UTC, kkkoltunov commented on src/test/java/edu/hw1/Task1Test.java
> +    void standart() {
название теста должно говорить само за себя и желательно начинаться с префикса `test`, давай давать разумные имена `testThat...And...Returned...`

также нужно поправить **везде** в коде

2023-10-10 16:49 UTC, Skiftare commented on src/test/java/edu/hw1/Task1Test.java
> +    void standart() {
Оххх, понял... Ещё раз всё перепроверю. Невнимательность.

2023-10-10 16:50 UTC, kkkoltunov commented
>  Лучше после ревью править файлы, и потом выкатывать один большой коммит, либо по файлам идти и сразу отправлять (файл-коммит, файл-коммит...)?

это дело вкуса, но кажется удобнее поправить все сразу и потом отправлять коммит (либо если устал закоммитить и продолжить дальше), не надо делать их так много)

>  И насколько гитхаб нормально делает code coverage? Idea показывает 100%, например, Task1. И вот где эти 5% искать? Писать тесты для чего, для импорта библиотек, инициализаций? (Я загуглил. Гуглид как-то не так походу, инфы 0)

честно говоря не знаю, тесты под импорт библиотек точно писать не надо, в целом у тебя код достаточно покрыт

2023-10-10 17:24 UTC, Skiftare commented on src/test/java/edu/hw1/Task1Test.java
> +    void standart() {
> название теста должно говорить само за себя и желательно начинаться с префикса `test`, давай давать разумные имена `testThat...And...Returned...`
> 
> также нужно поправить **везде** в коде

Ладно, сейчас я начинаю понимать шутки про то, зачем Java-программистам 2 монитора. Чтобы переменные влезали.

2023-10-11 15:40 UTC, kkkoltunov commented
я вижу что у тебя уже появились в этой же ветке файлы связанные с hw2, ты должен сделать отдельную ветку с названием hw2, и в нее пушить изменения

2023-10-11 15:47 UTC, kkkoltunov commented
в общем домашку я принимаю, ты молодец, хорошо поработал, давай в следующих домашках сохранять эту тенденцию и учитывать все правки и мои рекомендации, из замечаний оставлю: 
- следи за лишними пробелами, они все еще местами есть в конце или начале метода например
- следи за неймингом переменных, все еще есть переменные название которых не говорит само за себя например `funK`, `secN` и тд
- судя по coverage, покрыты не все возможные кейсы, старайся добивать полноценного покрытия

и пожалуйста давай комментарии на мои треды, что сделал, что не сделал, с чем согласен, какие есть сомнения и тд, возможно ты что-то считаешь лучше не делать, мне нужно твое мнение)

2023-10-11 15:51 UTC, Skiftare commented
> в общем домашку я принимаю, ты молодец, хорошо поработал, давай в следующих домашках сохранять эту тенденцию и учитывать все правки и мои рекомендации, из замечаний оставлю:
> 
> * следи за лишними пробелами, они все еще местами есть в конце или начале метода например
> * следи за неймингом переменных, все еще есть переменные название которых не говорит само за себя например `funK`, `secN` и тд
> * судя по coverage, покрыты не все возможные кейсы, старайся добивать полноценного покрытия
> 
> и пожалуйста давай комментарии на мои треды, что сделал, что не сделал, с чем согласен, какие есть сомнения и тд, возможно ты что-то считаешь лучше не делать, мне нужно твое мнение)

Безумие — это точное повторение одного и того же коммита. Раз за разом, в надежде на изменение. Это и есть безумие.

Если кратко по всему. После спортпрога очень тяжело писать много буковок, но это реально помогает - код становиться... Больше и читабельнее одновременно, хотя вот тесты я назвал так, что мне самому потребовались DisplyName, чтобы я понимал, что там твориться. secN я просто не придумал как поменять - второе n, чтобы IDE не ругалась, что я переданное использую. funK - так в дз написано, я нейминг не менял.

2023-10-11 15:53 UTC, Skiftare commented
> в общем домашку я принимаю, ты молодец, хорошо поработал, давай в следующих домашках сохранять эту тенденцию и учитывать все правки и мои рекомендации, из замечаний оставлю:
> 
> * следи за лишними пробелами, они все еще местами есть в конце или начале метода например
> * следи за неймингом переменных, все еще есть переменные название которых не говорит само за себя например `funK`, `secN` и тд
> * судя по coverage, покрыты не все возможные кейсы, старайся добивать полноценного покрытия
> 
> и пожалуйста давай комментарии на мои треды, что сделал, что не сделал, с чем согласен, какие есть сомнения и тд, возможно ты что-то считаешь лучше не делать, мне нужно твое мнение)

Пометьте пж ревью сделанным, чтобы я мог смержить. Конечно я и так и так это сделаю, но хочется чтоб красиво было

2023-10-12 01:57 UTC, merged