Hw5
Skiftare/Java2023 pull request #7
Opened 2023-11-07 13:53 UTC by Skiftare

2023-11-09 15:07 UTC, kkkoltunov requested changes
хорошая работа, поправь плиз замечания и зачтем

2023-11-09 15:07 UTC, kkkoltunov commented on src/main/java/edu/hw5/Task3.java
> +                // Ignore parsing exceptions and try the next formatter
вот так делать точно не стоит, все ошибки мы должны как-то обрабатывать, они для этого и существуют)

на работе за такое по рукам будут бить

давай добавим какое-то логирование или вывод в консоль, но так точно оставлять не будем

2023-11-09 15:07 UTC, kkkoltunov commented on src/test/java/edu/hw5/Task1Test.java
> +            //"2022-03-12, 20:20 - 2022-03-12, 23:50"
может убрать это?

2023-11-09 15:09 UTC, Skiftare commented on src/test/java/edu/hw5/Task1Test.java
> +            //"2022-03-12, 20:20 - 2022-03-12, 23:50"
Да. И DisplayName сейчас прикручу. Я забыл про него.

2023-11-10 12:08 UTC, kkkoltunov commented on src/main/java/edu/hw5/Task1.java
> +
следи за отступами, согласно кодстайлу обыно отсавлют 1 строку в таких случаях

2023-11-10 12:09 UTC, kkkoltunov commented
все ок, можно мерджить (а лучше добавь меня в коллабораторы чтобы я тоже мог это делать)

2023-11-10 12:18 UTC, Skiftare commented on src/main/java/edu/hw5/Task1.java
> +
Готово

2023-11-11 05:49 UTC, merged