Hw6
Skiftare/Java2023 pull request #8
Opened 2023-11-10 19:08 UTC by Skiftare

2023-11-14 16:11 UTC, kkkoltunov requested changes
с точки зрения выполнения задач - вопросов нет, логика нормальная, все реализовано верно

но есть вопросы к стилю написания кода, тут важно учитывать что работать ты будешь в команде, поэтому крайне важно писать код так, чтобы он без лишних комментов был понятен любому сокоманднику (сейчас реализация больше похоже на контест где надо что-то сделать быстро, давай это поправим)

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/PortDescription.java
> +    private String port;
зачем нужны все эти поля если они unused?)

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/PortDescription.java
> +    private String description;
давай поля стараться объявлять неизменяемыми, так будет более правильно с точки зрения ООП
```
private final String description;
```

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/AbstractFilter.java
> +    static AbstractFilter largerThan(long size) {
unused?

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/AbstractFilter.java
> +    static AbstractFilter regexContains(String regex) {
unused?

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/Task2.java
> +        String fileName = income;
а зачем здесь доп объявление, если можно сделать так?
```
public static String makeCopyName(Path path, String income) {
        String baseName = income.substring(0, income.lastIndexOf('.'));
        String extension = income.substring(income.lastIndexOf('.'));
        String newFileName = baseName + " — копия" + extension;
```

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/Task6.java
> +        for (int port : portSet) {
старайся брать себе за правило, что методы не должны быть большими по объему, здесь легко можно вынести логику в два отдельных метода

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/Task6.java
> +                resultOfScan.add(TSP_STRING + port + '\n');
`'\n'` - такие штуки старайся тоже выносить в константу

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/WikipediaParser.java
> +                "https://ru.wikipedia.org/wiki/%D0%A1%D0%BF%D0%B8%D1%81%D0%BE%D0%BA_%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2_TCP_%D0%B8_UDP";
почему не в константе?)

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/WikipediaParser.java
> +            for (Element row : rows) {
очень много логики в методе, давай разбивать ее

2023-11-14 16:11 UTC, kkkoltunov commented on src/test/java/edu/hw6/Рисунок1.png
это что?)

2023-11-14 16:11 UTC, kkkoltunov commented on src/main/java/edu/hw6/Tinkoff Bank Biggest Secret.txt
> +Big Uncopibable secret
где используется этот файл?

2023-11-14 16:11 UTC, kkkoltunov commented on src/test/java/edu/hw6/Task2Test.java
> +        assertThat(Files.exists(originalFile)).isTrue();
почему бы не заменить на `assertTrue`?

2023-11-14 16:11 UTC, kkkoltunov commented on src/test/java/edu/hw6/Task2Test.java
> +    void testThatCloneFileWithDifferentExtentionAndReturnedCheckOfExistCopy() throws IOException {
тест становится сложным и все слепленно вместе - читать такое тяжело

давай все тесты перепишем под концепци given-when-then (в коде можешь прям комменты оставлять, какой блок теста за какую часть концепции овтечает)

2023-11-14 16:25 UTC, Skiftare commented on src/main/java/edu/hw6/AbstractFilter.java
> +    static AbstractFilter largerThan(long size) {
Это надо оставить чтобы try-with-resourses работало.

2023-11-14 17:41 UTC, Skiftare commented on src/test/java/edu/hw6/Task2Test.java
> +    void testThatCloneFileWithDifferentExtentionAndReturnedCheckOfExistCopy() throws IOException {
> давай все тесты перепишем под концепци given-when-then (в коде можешь прям комменты оставлять, какой блок теста за какую часть концепции овтечает)

Я правильно понимаю, что всё что надо - это комментариями Given/When/Then разделить куски кода в тестах (и чётко разграничить область генерации тестовых данных с областью проверки с ожидаемым результатом), и рядом с соотв .параметром дополнительно сказать, что мы пытаемся делать?

2023-11-17 15:20 UTC, kkkoltunov reviewed
оставил еще замечания, старайся более внимательно относится к написанию кода, еще раз, мы не на олимпиаде, мы учимся писать код в команде и для продакшена)

здесь важно критиковать свой код и задавать вопросы, а понятно ли здесь? стараться разбивать на большее количество методов

плюс старайся следить за форматированием кода, и не забывать делать ПКМ по пакету, Reformat Code, и выбирать необходимые опции, или пользоваться хоткейми сразу при написании кода, опять же представь что твой код смотрит сокомандник)

2023-11-17 15:20 UTC, kkkoltunov commented on src/test/java/edu/hw6/Task1Test.java
> +        Given: // empty diskMap
вот с этими лейблами ты перегнул, давай без них, пример что я хочу от тебя получить
```
@Test
    @DisplayName("Тест на корректную отработку функции put() для самописного класса")
    void testThatPutValsAndReturnedCheckOfTheyExist() {
        // given empty diskMap
        DiskMap DISK_MAP = new DiskMap(TEST_FILE_PATH);

        // when put values
        diskMap.put("key1", "value1");
        diskMap.put("key2", "value2");

        // then values exists in map
        assertThat(diskMap.get("key1")).isEqualTo("value1");
        assertThat(diskMap.get("key2")).isEqualTo("value2");
    }
```

2023-11-17 15:20 UTC, kkkoltunov commented on src/test/java/edu/hw6/Task1Test.java
> +        Given: // empty diskMap
в тестах можно какую-то переменную которую ты используешь на протяжении всего теста именовать заглавными буквами как константу

2023-11-17 15:20 UTC, kkkoltunov commented on src/test/java/edu/hw6/Task1Test.java
> +        Given: // empty diskMap
основной посыл: относиться к тестам как к документации https://softwareengineering.stackexchange.com/questions/154615/are-unit-tests-really-used-as-documentation 

ты пишешь кейсы и стараешься продумать все нюансы системы, а потом другой разработчик может по твоим кейсам понять что происходит в системе и по таким кейсам легко понять функциональность, тк мы видим сразу юзер флоу

2023-11-17 15:20 UTC, kkkoltunov commented on src/test/java/edu/hw6/Рисунок1.png
ты так и не убрал?

2023-11-17 15:20 UTC, kkkoltunov commented on test_data.dat
> +key1:value1
старайся именовать классы с тестовыми данными и указывать к какому функционалу/задаче относится, а вообще лучше создать в test папку resources и туда класть по пакетам

2023-11-17 15:20 UTC, kkkoltunov commented on src/main/java/edu/hw6/Task6.java
> +    static HashSet<Integer> portSet = new HashSet<>();
а тут почему не так?
```
    private final static HashSet<Integer> PORT_SET = new HashSet<>();
```

2023-11-17 15:20 UTC, kkkoltunov commented on src/main/java/edu/hw6/Task5.java
> +        HttpClient client = HttpClient.newHttpClient();
почитай что такое try with resources, стоит сделать вот так для того чтобы избежать не закртых коннектов потом          
```
try (HttpClient client = HttpClient.newHttpClient()) {

        }
```

2023-11-17 15:20 UTC, kkkoltunov commented on src/main/java/edu/hw6/Task2.java
> +        String newFileName = baseName + " — копия" + extension;
почитай почему плохо конкатенировать через +, например тут https://www.baeldung.com/java-string-immutable

для таких операций используем `StringBuilder`

2023-11-17 15:20 UTC, kkkoltunov commented on src/main/java/edu/hw6/Task2.java
> +        String extension = income.substring(income.lastIndexOf('.'));
выносим точки в константы

2023-11-17 15:21 UTC, kkkoltunov commented on src/test/java/edu/hw6/Task2Test.java
> +    void testThatCloneFileWithDifferentExtentionAndReturnedCheckOfExistCopy() throws IOException {
отписал в тредах, основная мотивация подхода: тесты как документация

2023-11-17 15:30 UTC, Skiftare commented on src/test/java/edu/hw6/Рисунок1.png
Это надо для проверки существования. Сделать удаляемым?

2023-11-21 17:02 UTC, kkkoltunov commented on src/test/java/edu/hw6/Task2Test.java
> +    void testThatGetNumberOfCopyAndCreateNameForIt() {
делай отступы, тяжело читать слепленные строки вместе 
```
void testThatGetNumberOfCopyAndCreateNameForIt() {
        // given: name, extension and serial number of the copy
        String extension = ".txt";

        // when: create names for copy by the function
        String copyForFirst = createNameByNumber(ORIGIN_NAME, 1, extension);
        String copyForNotFisrt = createNameByNumber(ORIGIN_NAME, 1234, extension);

        // then: check for correct names for copies
        assertEquals("test - копия.txt", copyForFirst);
        assertEquals("test - копия (1234).txt", copyForNotFisrt);
    }
```

2023-11-21 17:03 UTC, kkkoltunov commented
как поправишь можешь вмерджить

2023-11-21 18:14 UTC, merged