Project3
Skiftare/Java2023 pull request #9
Opened 2023-11-18 20:50 UTC by Skiftare

Проект сырой.

2023-11-26 16:00 UTC, kkkoltunov commented
> И в процессе возник вопрос - а какие есть способы уменьшить количество глобальных переменных? А то эта куча мап... Плюс ещё различные значения. И константы, предположим, можно кидать в json, но что делать с таким количеством глобальных структур, я не придумал.

такая проблема действительно может быть, но в целом это ок, если переменных ставноится действительно много, то можно заводить статические Utils классы, в которые выносить константы. Еще большое количество переменных может говорить о том что класс содержит слишком много логики, поэтому ее стоит выделять на разные классы

2023-11-26 16:40 UTC, kkkoltunov requested changes
я оставил немного комментариев, код работает все ок, но читать его тяжело, давай поработаем над этим)

я пока выставлю оценку на платформе, а потом как поправишь, отпишишь мне и я подниму оценку!

2023-11-26 16:40 UTC, kkkoltunov commented on src/test/java/edu/project3/TestForLogAnalyzer.java
> +        //given: http-server & format
я ведь уже писал об отступах между строчками)
```
public void testThatGetHttpAndReturnsMetricFile() {
        //given: http-server & format
        String[] args = {"--path",
            "https://raw.githubusercontent.com/elastic/examples/master/Common%20Data%20Formats/nginx_logs/nginx_logs",
            "--format", "adoc"};

        //when: parse all logs
        LogAnalyzer logAnalyzer = new LogAnalyzer();
        LogAnalyzer.main(args);

        //then: check for same sizes in all maps
        assertEquals(22467, logAnalyzer.getTimeLocalMap().size());
        assertEquals(2660, logAnalyzer.getRemoteAddrMap().size());
        assertEquals(5, logAnalyzer.getRequestMap().size());
        assertEquals(6, logAnalyzer.getStatusMap().size());
        assertEquals(187, logAnalyzer.getBodyBytesSentMap().size());
        assertEquals(8, logAnalyzer.getHttpRefererMap().size());
        assertEquals(1, logAnalyzer.getRemoteUserMap().size());
        assertEquals (136, logAnalyzer.getHttpUserAgentMap().size());
    }
```

2023-11-26 16:40 UTC, kkkoltunov commented on src/test/java/edu/project3/TestForLogAnalyzer.java
> +        assertEquals(22467, logAnalyzer.getTimeLocalMap().size());
слишком много magic numbers из-за этого без контекста тяжело понять что происходит и проверяется в тесте, в таких случаях выход только один, делать под каждый ассерт отдельный метод и давать ему читабельный нейминг, а затем использовать эти методы во всех тестовых методах, то есть так
```   
        //then: check for same sizes in all maps
        thenCheckTimeLocalMap(22467, logAnalyzer.getTimeLocalMap().size());
        /// ...
    }
    
    void thenCheckTimeLocalMap(int expectedSize, int actualSize) {
        assertEquals(expectedSize, actualSize);
    }
```

2023-11-26 16:40 UTC, kkkoltunov commented on src/test/java/edu/project3/TestForLogAnalyzer.java
> +        assertEquals(22467, logAnalyzer.getTimeLocalMap().size());
это необходимо поправить во всех тестовых методах

2023-11-26 16:40 UTC, kkkoltunov commented on src/test/java/edu/project3/resources/oneMoreFolder/log1.txt
нейминг oneMoreFolder уже перебор, давай по бизнес смыслу называть директории

2023-11-26 16:40 UTC, kkkoltunov commented on src/test/java/edu/project3/resources/log1.txt
ты можешь создать тестовую папку с ресурсами аналогично пакету main, то есть так и туда класть ресурсы для тестов

<img width="448" alt="Снимок экрана 2023-11-26 в 19 11 06" src="https://github.com/Skiftare/Java2023/assets/70812280/8aa6f10a-f213-442a-96b7-89c391d70fb7">

2023-11-26 16:40 UTC, kkkoltunov commented on src/main/java/edu/project3/ResponseCodeParser.java
> +
пустая строчка?

2023-11-26 16:40 UTC, kkkoltunov commented on src/main/java/edu/project3/ResponseCodeParser.java
> +            Elements rows = doc.select("table.standard-table tbody tr");
`"table.standard-table tbody tr"` как проверяющих код модет понять что это значит?)

ты если прикручиваешь библиотеки, то пиши документации к методам, выноси подобные запросы в константы, чтобы по их имени можно было понять что происходит

2023-11-26 16:40 UTC, kkkoltunov commented on src/main/java/edu/project3/ResponseCodeParser.java
> +                    return row.select("td").get(1).text();
тут аналогично комменту выше, что значат эти константы?

2023-11-26 16:40 UTC, kkkoltunov commented on src/main/java/edu/project3/ResponseCodeParser.java
> +            LOGGER.info(e.getMessage());
логи - это один из инструментов по которым мы можем понять что пошло не так в нашем приложении, в них стоит складывать как можно больше контекста и бизнес объяснений, хороший лог:
```
} catch (IOException e) {
            LOGGER.error("Error while connecting {}, message {} ", HTTP_URL, e.getMessage(), e);
        }
```

2023-11-26 16:40 UTC, kkkoltunov commented on src/main/java/edu/project3/LogAnalyzer.java
> +public class LogAnalyzer {
помню писал точно также свои домашки в универе, в одном классе, прям всплакнул от ностальгии

ps это абсолютно нормально когда мы учимся, но не очень приянто с точки зрения работы, там за такое бьют по рукам, поэтому скинул тебе в личку проект, чтобы ты посмотрел как можно эту логику растолкать по разным классам

собственно из-за того что у тебя все прибито гвоздями к одному классу, то получается много глобальных переменных

2023-11-26 16:40 UTC, kkkoltunov commented on src/main/java/edu/project3/LogAnalyzer.java
> +public class LogAnalyzer {
думаю тебе стоит ознакомиться с примером, который я тебе скинул и попробовать переписать эту логику, потому что с точки зрения функционирования программы все ок, а вот с точки зрения кода, есть что улучшить)

2023-12-01 10:26 UTC, Skiftare commented
У меня была идея сделать по классу на каждый вывод - но я решил, что это уже перебор и оверинжениринг.

2023-12-09 07:48 UTC, Skiftare commented
Я посмотрел код. Там абстракция на adoc/markdown. Это у меня было зашито в Table, так что  рефакторинг шёл там. Помимо этого, чуть изменил ReportGenerator.

2023-12-14 16:13 UTC, kkkoltunov commented
можешь мерджить, принято!

2023-12-14 16:19 UTC, merged